"""Initial migration

Revision ID: de07cca94b84
Revises: 
Create Date: 2026-01-02 18:43:57.533438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de07cca94b84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id', 'account_number', name='uq_broker_account')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_allocation_quantity_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.create_index('idx_allocations_goal', ['goal_id'], unique=False)
        batch_op.create_index('idx_allocations_owner', ['owner_id'], unique=False)
        batch_op.create_index('idx_allocations_stock_account', ['stock_id', 'account_id'], unique=False)

    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('ratio_from', sa.Integer(), nullable=False),
    sa.Column('ratio_to', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('detected_automatically', sa.Boolean(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("action_type IN ('split', 'bonus', 'merger', 'demerger')", name='ck_action_type'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('financial_year', sa.String(length=9), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('discrepancies_found', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("file_type IN ('tradebook', 'taxpnl')", name='ck_file_type'),
    sa.CheckConstraint("status IN ('pending', 'success', 'partial', 'failed')", name='ck_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('day_high', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('day_low', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id')
    )
    op.create_table('realized_pnl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('buy_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sell_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('holding_days', sa.Integer(), nullable=False),
    sa.Column('tax_term', sa.String(length=4), nullable=False),
    sa.Column('financial_year', sa.String(length=9), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('brokerage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stt', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('other_charges', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("source IN ('imported', 'calculated')", name='ck_source'),
    sa.CheckConstraint("tax_term IN ('STCG', 'LTCG')", name='ck_tax_term'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('realized_pnl', schema=None) as batch_op:
        batch_op.create_index('idx_realized_pnl_account', ['account_id'], unique=False)
        batch_op.create_index('idx_realized_pnl_exit_date', ['exit_date'], unique=False)
        batch_op.create_index('idx_realized_pnl_fy', ['financial_year'], unique=False)
        batch_op.create_index('idx_realized_pnl_stock', ['stock_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.String(length=4), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('trade_datetime', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("trade_type IN ('buy', 'sell')", name='ck_trade_type'),
    sa.CheckConstraint('price > 0', name='ck_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_quantity_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trade_id', name='uq_account_trade')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('idx_trades_fifo', ['stock_id', 'account_id', 'trade_type', 'trade_datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('idx_trades_fifo')

    op.drop_table('trades')
    with op.batch_alter_table('realized_pnl', schema=None) as batch_op:
        batch_op.drop_index('idx_realized_pnl_stock')
        batch_op.drop_index('idx_realized_pnl_fy')
        batch_op.drop_index('idx_realized_pnl_exit_date')
        batch_op.drop_index('idx_realized_pnl_account')

    op.drop_table('realized_pnl')
    op.drop_table('price_cache')
    op.drop_table('import_logs')
    op.drop_table('corporate_actions')
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.drop_index('idx_allocations_stock_account')
        batch_op.drop_index('idx_allocations_owner')
        batch_op.drop_index('idx_allocations_goal')

    op.drop_table('allocations')
    op.drop_table('stocks')
    op.drop_table('accounts')
    op.drop_table('sectors')
    op.drop_table('owners')
    op.drop_table('goals')
    op.drop_table('brokers')
    # ### end Alembic commands ###
